/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    BrandMark: typeof import('./src/components/BrandMark.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CalcTabs: typeof import('./src/components/CalcTabs.vue')['default']
    ConcretePour: typeof import('./src/components/fx/ConcretePour.vue')['default']
    Contacs: typeof import('./src/components/Contacs.vue')['default']
    CrossSell: typeof import('./src/components/CrossSell.vue')['default']
    CtaSection: typeof import('./src/components/CtaSection.vue')['default']
    FaqSection: typeof import('./src/components/FaqSection.vue')['default']
    FloatingContacts: typeof import('./src/components/FloatingContacts.vue')['default']
    GranulesFall: typeof import('./src/components/fx/GranulesFall.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    KeramzitCalculator: typeof import('./src/components/keramzit/KeramzitCalculator.vue')['default']
    KeramzitPrices: typeof import('./src/components/keramzit/KeramzitPrices.vue')['default']
    Marquee: typeof import('./src/components/fx/Marquee.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    NotFoundBlock: typeof import('./src/components/landing/NotFoundBlock.vue')['default']
    NumberTicker: typeof import('./src/components/fx/NumberTicker.vue')['default']
    PageHero: typeof import('./src/components/PageHero.vue')['default']
    PhoneInput: typeof import('./src/components/Inputs/PhoneInput.vue')['default']
    ProcessSection: typeof import('./src/components/ProcessSection.vue')['default']
    ProductDetails: typeof import('./src/components/landing/ProductDetails.vue')['default']
    ProductGrid: typeof import('./src/components/ProductGrid.vue')['default']
    ProductHero: typeof import('./src/components/landing/ProductHero.vue')['default']
    ProductLinks: typeof import('./src/components/ProductLinks.vue')['default']
    Pumps: typeof import('./src/components/Pumps.vue')['default']
    RequestButton: typeof import('./src/components/RequestButton.vue')['default']
    RequestDialog: typeof import('./src/components/RequestDialog.vue')['default']
    Reveal: typeof import('./src/components/fx/Reveal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeading: typeof import('./src/components/SectionHeading.vue')['default']
    SiblingLinks: typeof import('./src/components/landing/SiblingLinks.vue')['default']
    SpotlightCard: typeof import('./src/components/fx/SpotlightCard.vue')['default']
    StatsSection: typeof import('./src/components/StatsSection.vue')['default']
    TickerStrip: typeof import('./src/components/TickerStrip.vue')['default']
    UsernameInput: typeof import('./src/components/Inputs/UsernameInput.vue')['default']
    UsesGrid: typeof import('./src/components/UsesGrid.vue')['default']
    VolumeEstimator: typeof import('./src/components/VolumeEstimator.vue')['default']
  }
}
