/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/avtobetononasos': RouteRecordInfo<'/avtobetononasos', '/avtobetononasos', Record<never, never>, Record<never, never>>,
    '/beton/[grade]': RouteRecordInfo<'/beton/[grade]', '/beton/:grade', { grade: ParamValue<true> }, { grade: ParamValue<false> }>,
    '/keramzit/': RouteRecordInfo<'/keramzit/', '/keramzit', Record<never, never>, Record<never, never>>,
    '/keramzit/[slug]': RouteRecordInfo<'/keramzit/[slug]', '/keramzit/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/keramzitobeton': RouteRecordInfo<'/keramzitobeton', '/keramzitobeton', Record<never, never>, Record<never, never>>,
    '/pesok-scheben': RouteRecordInfo<'/pesok-scheben', '/pesok-scheben', Record<never, never>, Record<never, never>>,
  }
}
